# Generated by Django 6.0.4 on 2026-04-12 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Keywords"
            ),
        ),
    ]
