# Generated by Django 6.0.4 on 2026-04-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sevo_blog", "0003_postimage_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True, to="sevo_blog.category", verbose_name="Categories"
            ),
        ),
    ]
